module.exports = [
  { slug: 'labour', name: 'Labour', nameHi: 'मजदूर', icon: 'construction', sortOrder: 1 },
  { slug: 'mason', name: 'Mason', nameHi: 'राजमिस्त्री', icon: 'brick', sortOrder: 2 },
  { slug: 'painter', name: 'Painter', nameHi: 'पेंटर', icon: 'format-paint', sortOrder: 3 },
  { slug: 'electrician', name: 'Electrician', nameHi: 'इलेक्ट्रीशियन', icon: 'electrical-services', sortOrder: 4 },
  { slug: 'plumber', name: 'Plumber', nameHi: 'प्लंबर', icon: 'plumbing', sortOrder: 5 },
  { slug: 'carpenter', name: 'Carpenter', nameHi: 'बढ़ई', icon: 'carpenter', sortOrder: 6 },
  { slug: 'welder', name: 'Welder', nameHi: 'वेल्डर', icon: 'build', sortOrder: 7 },
  { slug: 'driver', name: 'Driver', nameHi: 'ड्राइवर', icon: 'directions-car', sortOrder: 8 },
  { slug: 'delivery', name: 'Delivery', nameHi: 'डिलीवरी', icon: 'local-shipping', sortOrder: 9 },
  { slug: 'cleaning', name: 'House Cleaning', nameHi: 'सफाई', icon: 'cleaning-services', sortOrder: 10 },
  { slug: 'cook', name: 'Cook', nameHi: 'रसोइया', icon: 'restaurant', sortOrder: 11 },
  { slug: 'security', name: 'Security Guard', nameHi: 'सिक्योरिटी', icon: 'security', sortOrder: 12 },
  { slug: 'gardener', name: 'Gardener', nameHi: 'माली', icon: 'yard', sortOrder: 13 },
  { slug: 'ac-repair', name: 'AC / Appliance Repair', nameHi: 'एसी मरम्मत', icon: 'ac-unit', sortOrder: 14 },
  { slug: 'loader', name: 'Loader / Hamal', nameHi: 'हम्माल', icon: 'inventory', sortOrder: 15 },
  { slug: 'event-staff', name: 'Event Staff', nameHi: 'इवेंट स्टाफ', icon: 'event', sortOrder: 16 },
  { slug: 'tailor', name: 'Tailor', nameHi: 'दर्जी', icon: 'content-cut', sortOrder: 17 },
  { slug: 'beautician', name: 'Beautician', nameHi: 'ब्यूटीशियन', icon: 'spa', sortOrder: 18 },
  { slug: 'tutor', name: 'Tutor', nameHi: 'ट्यूटर', icon: 'school', sortOrder: 19 },
  { slug: 'shop-helper', name: 'Shop Helper', nameHi: 'दुकान सहायक', icon: 'storefront', sortOrder: 20 },
  { slug: 'warehouse', name: 'Warehouse', nameHi: 'गोदाम', icon: 'warehouse', sortOrder: 21 },
  { slug: 'other', name: 'Other', nameHi: 'अन्य', icon: 'more-horiz', sortOrder: 22 },
];
